### ISSUE TITLE
Are the algorithms in UpscaleProcessor.cs neural ? powered by some sort of neural network or similar processes ?

### ISSUE THREAD

**Issue by electrum-bowie** [DevsDaddy/UnityXScaling#5]
Just a really really quick question because I really can't tell if they're basic algorithms or some kind of AI models.

**Comment by DevsDaddy** [comment]
The algorithm itself has been trained on the neural network and produces averaged data based on its weighting. It is quite expensive to connect Real-Time processing of a neural network, and processing of each frame will grow 10-15 times, which is not suitable for Runtime
